
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqtgzrtkoeyzklwnpjre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxdGd6cnRrb2V5emtsd25wanJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjU1OTcsImV4cCI6MjA2MjA0MTU5N30.RoNR90zzTJs1ByaMp4muuBotxfGwBaY6VTeDyEaYdaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
